In [4]:
# IMPORT THE LIBRARIES
import numpy as np

In [3]:
# CREATING AN ARRAY
a = np.array([1,2,3,4,5],)
a

array([1, 2, 3, 4, 5])

In [5]:
# CHECKING THE DIMENSION OF THE ARRAY
a.ndim

1

In [6]:
b = np.array([[1,2,3,4,5],[6,7,8,9,0]])
b

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [7]:
b.ndim

2

In [8]:
var4=np.zeros((4,2,3))

In [9]:
var4

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

## FUNCTIONS IN NUMPY

In [10]:
var=np.array([20,30,40,50])

In [11]:
var

array([20, 30, 40, 50])

In [12]:
var.ndim

1

In [13]:
type(var)

numpy.ndarray

In [14]:
var.argmax()

3

In [15]:
var.argmin()

0

In [18]:
arr1 = np.array([1,2.4,3,4,5,6])
arr1

array([1. , 2.4, 3. , 4. , 5. , 6. ])

In [19]:
arr1.dtype

dtype('float64')

In [21]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
a=np.arange(12)

In [24]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
np.arange(12).reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])